import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat as GFont, Josefin_Slab as MonoFont } from 'next/font/google'
import "./globals.css";
import { MutableRefObject } from "react";

const getShowFont = localFont({
  src: "./fonts/Get Show.woff",
  variable: "--font-get-show-sans",
  weight: "100 900",
});

const mainFont = GFont({
  subsets: ['latin']
})

const monoFont = MonoFont({
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Jean-Cédric T. – Senior Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${mainFont.className} antialiased`}
      >
        <header id="top" className="fixed w-full z-10 bg-transparent print:container print:mx-auto print:shadow-none print:relative print:mb-6">
          <div className="container backdrop-blur-sm max-w-6xl mx-auto px-6 md:px-40 flex justify-between items-center print:p-0 print:justify-normal bg-gradient-to-b from-stone-50/10 to-stone-400/10 shadow-xl shadow-black/30 print:bg-none print:shadow-none">
            <h1 className="text-2xl font-bold print:me-4">Jean-Cédric T.</h1>
            <p className='hidden print:inline'>Senior software engineer</p>
            
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
